spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/definex}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password123}
  jpa:
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      secret-key: ${JWT_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${JWT_EXPIRATION:86400000}

file:
  upload-dir: /home/muaz/Desktop/TaskManagement
